branch-defaults:
  default:
    environment: acheev-prod
    group_suffix: null
deploy:
  artifact: deploy.zip
environment-defaults:
  acheev-prod:
    branch: null
    repository: null
global:
  application_name: acheev
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js 14
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application
